// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2083.robot;
    
import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.CANTalon;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {

	// Drive Wheels
    public static final int LEFT_FORWARD_MOTOR_CONTROLLER_ID = 1;
    public static final int LEFT_BACK_MOTOR_CONTROLLER_ID = 5;
    public static final int RIGHT_FORWARD_MOTOR_CONTROLLER_ID = 2;
    public static final int RIGHT_BACK_MOTOR_CONTROLLER_ID = 12;

    public static CANJaguar leftForwardMotorController;
    public static CANJaguar leftBackMotorController;
    public static CANJaguar rightForwardMotorController;
    public static CANJaguar rightBackMotorController;
    
    // Arm
    public static final int ARM_BAR_MOTOR_CONTROLLER_ID = 18;
    public static CANTalon armBarMotorController;

    // Input Controls
    public static final int JS_DRIVER_PORT = 0;
    public static final int JS_DRIVER_ARM_BUTTON = 5;

    public static void init() {
    	
    }
}
