// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2083.TeamBlitzRobot2015;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {

    public static final int leftForwardMotorControllerID = 12;
    public static final int leftBackMotorControllerID = 7;
    public static final int rightForwardMotorControllerID = 1;
    public static final int rightBackMotorControllerID = 8;

    public static CANJaguar leftForwardMotorController;
    public static CANJaguar leftBackMotorController;
    public static CANJaguar rightForwardMotorController;
    public static CANJaguar rightBackMotorController;
    
    public static boolean auto;
    public static double autoY = 0;
    public static double autoTimer = -1;
    public static double autoDriveTime = 0;
    public static int autoDistSelectChannel = 5;
    

    public static int downButton = 4;
    public static int upButton = 3;
    public static int openButton = 2;
    public static int closeButton = 1;

    public static CANJaguar gripperLeftMotorController;
    public static CANJaguar gripperRightMotorController;
    public static CANTalon fourBarMotorController;
    public static final int gripperLeftMotorControllerID = 5;
    public static final int gripperRightMotorControllerID = 2;
    public static final int fourBarMotorControllerID = 3;
    public static final double gripperMotorVoltageLimit = 9.0;
    public static final double gripperMotorCurrentLimit = 15.0;
    public static final int xboxLeftTriggerAxisNum = 2; 
    public static final int xboxRightTriggerAxisNum = 3; 


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {}
}
